name: Calling Reusable Workflows
on:
  workflow_dispatch:
jobs:
  calling:
    uses: ./.github/workflows/ann.yaml
  using_output:
    runs-on: ubuntu-latest
    needs: calling
    steps:
      - run: echo ${{ needs.calling.outputs.date }}
    
