name: Calling Reusable Workflows
on:
  workflow_dispatch:
jobs:
  calling:
    uses: ./.github/workflows/usingreusable.yaml
  using_output:
    runs-on: ubuntu-latest
    needs: usingreusable
    steps:
      - run: echo ${{ needs.usingreusable.outputs.date }}
    
