name: Repositor
on:
 push:
 pull_request:
  types: [opened, assigned, reopened, synchronized ]
 issues:
  types: [opened]
jobs:
 chekout_test:
  runs-on: ubuntu-latest
  steps:
    - run:
        echo $GITHUB_SHA
        echo $GITHUB_REF
    - uses: actions/checkout@v3
